#ifndef CONFIG_GAME_H_
#define CONFIG_GAME_H_

#define SERIAL_BAUD_RATE 115200

#define LED_PIN D3
#define LED_SIGNAL_ON HIGH
#define LED_SIGNAL_OFF LOW

#define BUTTON_PIN D4
#define BUTTON_SIGNAL_ON HIGH
#define BUTTON_SIGNAL_OFF LOW

#endif
